directory/urls.py
from django.urls import re_path

import directory.views as directory
import personalacc.views as personalacc
from personalacc.apps import PersonalaccConfig

app_name = PersonalaccConfig.name

urlpatterns = [
    re_path(r"^$", directory.DirectoryList.as_view(), name="list"),
    # ServicesCategory
    re_path(r"^categories/create/$", directory.ServicesCategoryCreateView.as_view(), name="category_create"),
    re_path(
        r"^categories/update/(?P<pk>\d+)/$", directory.ServicesCategoryUpdateView.as_view(), name="category_update"
    ),
    re_path(
        r"^categories/delete/(?P<pk>\d+)/$", directory.ServicesCategoryDeleteView.as_view(), name="category_delete"
    ),
    # Services
    re_path(r"^services/create/category/(?P<pk>\d+)/$", directory.ServicesCreateView.as_view(), name="services_create"),
    re_path(r"^services/read/category/(?P<pk>\d+)/$", directory.ServicesListView.as_view(), name="services"),
    re_path(r"^services/update/(?P<pk>\d+)/$", directory.ServicesUpdateView.as_view(), name="services_update"),
    re_path(r"^services/delete/(?P<pk>\d+)/$", directory.ServicesDeleteView.as_view(), name="services_delete"),
    # City
    re_path(r"^city/create/$", directory.CityCreateView.as_view(), name="city_create"),
    re_path(r"^city/update/(?P<pk>\d+)/$", directory.CityUpdateView.as_view(), name="city_update"),
    re_path(r"^city/delete/(?P<pk>\d+)/$", directory.CityDeleteView.as_view(), name="city_delete"),
    # Street
    re_path(r"^street/create/city/(?P<pk>\d+)/$", directory.StreetCreateView.as_view(), name="street_create"),
    re_path(r"^street/read/city/(?P<pk>\d+)/$", directory.StreetListView.as_view(), name="streets"),
    re_path(r"^street/update/(?P<pk>\d+)/$", directory.StreetUpdateView.as_view(), name="street_update"),
    re_path(r"^street/delete/(?P<pk>\d+)/$", directory.StreetDeleteView.as_view(), name="street_delete"),
    # House
    re_path(r"^house/create/street/(?P<pk>\d+)/$", directory.HouseCreateView.as_view(), name="house_create"),
    re_path(r"^house/read/street/(?P<pk>\d+)/$", directory.HouseListView.as_view(), name="house"),
    re_path(r"^house/update/(?P<pk>\d+)/$", directory.HouseUpdateView.as_view(), name="house_update"),
    re_path(r"^house/delete/(?P<pk>\d+)/$", directory.HouseDeleteView.as_view(), name="house_delete"),
    # Appartaments
    re_path(
        r"^appartaments/create/house/(?P<pk>\d+)/$",
        directory.AppartamentsCreateView.as_view(),
        name="appartaments_create",
    ),
    re_path(r"^appartaments/read/house/(?P<pk>\d+)/$", directory.AppartamentsListView.as_view(), name="appartaments"),
    re_path(
        r"^appartaments/update/(?P<pk>\d+)/$", directory.AppartamentsUpdateView.as_view(), name="appartaments_update"
    ),
    re_path(
        r"^appartaments/delete/(?P<pk>\d+)/$", directory.AppartamentsDeleteView.as_view(), name="appartaments_delete"
    ),
    # Residents
    re_path(r"^resident/read/$", directory.ResidentsListView.as_view(), name="residents"),
    re_path(r"^resident/create/$", directory.ResidentsCreateView.as_view(), name="residents_create"),
    re_path(r"^resident/update/(?P<pk>\d+)/$", directory.ResidentsUpdateView.as_view(), name="residents_update"),
    re_path(r"^resident/delete/(?P<pk>\d+)/$", directory.ResidentsDeleteView.as_view(), name="residents_delete"),
]

invoice/urls.py
from django.conf import settings
from django.urls import re_path, path
import invoice.views as invoice
from invoice.apps import InvoiceConfig

app_name = InvoiceConfig.name

urlpatterns = [
    re_path(r"^$", invoice.InvoiceViews.as_view(), name="invoice"),
    # path('invoice/', invoice.main, name='invoice'),
]

if settings.DEBUG:
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns
    urlpatterns += staticfiles_urlpatterns()

newcity/urls.py
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path

import mainapp.views as mainapp

urlpatterns = [
    path("", mainapp.main, name="main"),
    path("auth/", include("authnapp.urls", namespace="auth")),
    path("person/", include("personalacc.urls", namespace="person")),
    path("directory/", include("directory.urls", namespace="directory")),
    path("invoice/", include("invoice.urls", namespace="invoice")),
    path("admin/", admin.site.urls, name="admin"),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

directory/models.py
from django.db import models

# Create your models here.

directory/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db import transaction
from django.forms.models import BaseInlineFormSet, inlineformset_factory
from django.shortcuts import HttpResponseRedirect, get_object_or_404, render
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, DeleteView, ListView, UpdateView

from authnapp.admin import UserCreationForm
from authnapp.forms import AppartamentFormset
from authnapp.managers import UserManager
from authnapp.models import User
from directory.forms import (
    AppartamentFormSet,
    AppartamentsEditForm,
    CityEditForm,
    HouseEditForm,
    ResidentsEditForm,
    ServicesCategoryEditForm,
    ServicesEditForm,
    StreetEditForm,
)
from mainapp.models import Appartament, City, House, Services, ServicesCategory, Street, UserProfile


class DirectoryList(LoginRequiredMixin, ListView):
    model = User
    template_name = "directory/directory_list.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["residents"] = User.objects.filter(is_staff=False).filter(is_superuser=False)
        context["categories"] = ServicesCategory.objects.all()
        context["city"] = City.objects.all()
        return context


"""
================
PRODUCT CATEGOTY
================
"""


class ServicesCategoryCreateView(LoginRequiredMixin, CreateView):
    model = ServicesCategory
    template_name = "directory/category_update.html"
    success_url = reverse_lazy("directory:list")
    form_class = ServicesCategoryEditForm


class ServicesCategoryUpdateView(LoginRequiredMixin, UpdateView):
    model = ServicesCategory
    template_name = "directory/category_update.html"
    success_url = reverse_lazy("directory:list")
    form_class = ServicesCategoryEditForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Категории/редактирование"
        return context


class ServicesCategoryDeleteView(LoginRequiredMixin, DeleteView):
    model = ServicesCategory
    template_name = "directory/category_delete.html"
    success_url = reverse_lazy("directory:list")

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.is_active = False
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())


"""
=========
SERVICES
=========
"""


class ServicesListView(LoginRequiredMixin, ListView):
    model = Services
    template_name = "directory/services.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["category"] = get_object_or_404(ServicesCategory, pk=self.kwargs["pk"])
        context["services"] = Services.objects.filter(category__pk=self.kwargs["pk"]).order_by("name")
        return context


class ServicesCreateView(LoginRequiredMixin, CreateView):
    model = Services
    template_name = "directory/services_update.html"
    success_url = reverse_lazy("directory:list")
    form_class = ServicesEditForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Тариф/создание"
        return context


class ServicesUpdateView(LoginRequiredMixin, UpdateView):
    model = Services
    template_name = "directory/services_update.html"
    success_url = reverse_lazy("directory:list")
    form_class = ServicesEditForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Тариф/редактирование"
        return context


class ServicesDeleteView(LoginRequiredMixin, DeleteView):
    model = Services
    template_name = "directory/services_delete.html"
    success_url = reverse_lazy("directory:list")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Тариф/удаление"
        return context

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.is_active = False
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())


"""
==========
   CITY
==========
"""


class CityCreateView(LoginRequiredMixin, CreateView):
    model = City
    template_name = "directory/city_update.html"
    success_url = reverse_lazy("directory:list")
    form_class = CityEditForm


class CityUpdateView(LoginRequiredMixin, UpdateView):
    model = City
    template_name = "directory/city_update.html"
    success_url = reverse_lazy("directory:list")
    form_class = CityEditForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Города/редактирование"
        return context


class CityDeleteView(LoginRequiredMixin, DeleteView):
    model = City
    template_name = "directory/city_delete.html"
    success_url = reverse_lazy("directory:list")

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.is_active = False
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())


"""
==========
  STREET
==========
"""


class StreetListView(LoginRequiredMixin, ListView):
    model = Street
    template_name = "directory/streets.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["city"] = get_object_or_404(City, pk=self.kwargs["pk"])
        context["streets"] = Street.objects.filter(city__pk=self.kwargs["pk"]).order_by("street")
        return context


class StreetCreateView(LoginRequiredMixin, CreateView):
    model = Street
    template_name = "directory/street_update.html"
    success_url = reverse_lazy("directory:list")
    form_class = StreetEditForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["city"] = self.kwargs["pk"]
        context["title"] = "Улица/создание"
        return context


class StreetUpdateView(LoginRequiredMixin, UpdateView):
    model = Street
    template_name = "directory/street_update.html"
    success_url = reverse_lazy("directory:list")
    form_class = StreetEditForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["city"] = self.kwargs["pk"]
        context["title"] = "Улица/редактирование"
        return context


class StreetDeleteView(LoginRequiredMixin, DeleteView):
    model = Street
    template_name = "directory/street_delete.html"
    success_url = reverse_lazy("directory:list")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Улица/удаление"
        return context

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.is_active = False
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())


"""
=========
  HOUSE
=========
"""


class HouseListView(LoginRequiredMixin, ListView):
    model = House
    template_name = "directory/house.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["street"] = get_object_or_404(Street, pk=self.kwargs["pk"])
        context["house"] = House.objects.filter(street__pk=self.kwargs["pk"]).order_by("street")
        return context


class HouseCreateView(LoginRequiredMixin, CreateView):
    model = House
    template_name = "directory/house_update.html"
    success_url = reverse_lazy("directory:list")
    form_class = HouseEditForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Дом/создание"
        return context


class HouseUpdateView(LoginRequiredMixin, UpdateView):
    model = House
    template_name = "directory/house_update.html"
    success_url = reverse_lazy("directory:list")
    form_class = HouseEditForm

    # def get_queryset(self):
    #     return House.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Дом/редактирование"

        if self.request.POST:
            context["appartament_form"] = AppartamentFormSet(self.request.POST, instance=self.object)
        else:
            queryset = self.object.appartament_set.filter(is_active=True).select_related()
            formset = AppartamentFormSet(instance=self.object, queryset=queryset)
            context["appartament_form"] = formset
        return context

    # def post(self, request, *args, **kwargs):
    #     self.object = self.get_object()
    #     form_class = self.get_form_class()
    #     form = self.get_form(form_class)
    #     formset = AppartamentFormset(self.request.POST, instance=self.object)

    #     if form.is_valid() and formset.is_valid():
    #         return self.form_valid(form, formset)

    #     return self.form_invalid(form, formset)

    def form_valid(self, form):
        """
        Called if all forms are valid. Creates a Author instance along
        with associated books and then redirects to a success page.
        """
        context = self.get_context_data()
        appartament_form = context["appartament_form"]

        with transaction.atomic():
            self.object = form.save()
            if appartament_form.is_valid():
                appartament_form.instance = self.object
                appartament_form.save()

        return super().form_valid(form)


class HouseDeleteView(LoginRequiredMixin, DeleteView):
    model = House
    template_name = "directory/house_delete.html"
    success_url = reverse_lazy("directory:list")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Дом/удаление"
        return context

directory/templates/directory/appartaments.html
{% extends 'directory/base.html' %}
{% load staticfiles %}

{% load crispy_forms_tags %}

{% block menu %}
    {% include 'directory/includes/inc_menu.html' %}
{% endblock menu %}

{% block content %}
    <div class="row  mt-5  mb-3  d-flex justify-content-between">
        <h4 class="col">Адрес дома: <span class="text-700">{{ house.street }}, дом №{{ house.number }}</span></h4>
        <div class="form-group">
            <a href="{% url 'directory:appartaments_create' house.pk %}" class="btn btn-outline-primary btn-sm" role="button">Добавить квартиру</a>
            <a class="btn  btn-outline-secondary btn-sm" onclick="javascript:history.back(); return false;" role="button">Назад</a>
        </div>
        
    </div>
    <div class="manager-area__counters-history  mb-5">
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">ID</th>
                    <th class="text-left" scope="col">Квартира №</th>
                    <th scope="col">Комната</th>
                    <th scope="col">Владелец</th>
                    <th scope="col">Площадь</th>
                    <th scope="col">Кол-во проживающих</th>
                    <th scope="col">Редактировать</th>
                    <th scope="col">удалиь</th>
                </tr>
            </thead>

            {% for item in appartaments %}
            <tbody>
                <tr>
                    <td>{{ item.id }}</td>
                    <td class="text-left">кв. №{{ item.number }}</td>
                    <td>{{ item.add_number }}</td>
                    <td>{{ item.user.name }}</td>
                    <td>{{ item.sq_appart }}</td>
                    <td>{{ item.num_owner }}</td>
                    <td><a href="{% url 'directory:appartaments_update' item.pk %}" type="button" class="btn btn-outline-warning btn-sm" role="button">Редактировать</a></td>
                    <td><a href="{% url 'directory:appartaments_delete' item.pk %}" class="text-danger text-decoration-none">удалить</a></td>
                </tr>
            </tbody>
            {% endfor %}

        </table> 
    </div>
{% endblock %}

directory/templates/directory/appartaments_delete.html
{% extends 'directory/base.html' %}
{% load staticfiles %}

{% block menu %}
    {% include 'directory/includes/inc_menu.html' %}
{% endblock menu %}

{% block content %}
    <div class="directory__form">
        <p class="category_delete--text">Уверены, что хотите удалить <strong>квартиру № {{ object.number }} ({{ object.house }})</strong>?</p> 
        <div class="category__form">
            <form action="{% url 'directory:appartaments_delete' object.pk %}" method="post">
                {% csrf_token %}

                <div class="form-group  d-flex  justify-content-around  mt-5">
                    <input class="btn  btn-danger" type="submit" value="удалить">
                    <a class="btn  btn-success" role="button" onclick="javascript:history.back(); return false;">отмена</a>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

directory/templates/directory/category_delete.html
{% extends 'directory/base.html' %}
{% load staticfiles %}

{% block menu %}
    {% include 'directory/includes/inc_menu.html' %}
{% endblock menu %}

{% block content %}
    <div class="directory__form">
        <p class="category_delete--text">Уверены, что хотите удалить категорию <strong>{{ object.name }}</strong>?</p> 
        <div class="category__form">
            <form action="{% url 'directory:category_delete' object.pk %}" method="post">
                {% csrf_token %}

                <div class="form-group  d-flex  justify-content-around  mt-5">
                    <input class="btn  btn-danger" type="submit" value="удалить">
                    <a class="btn  btn-success" role="button" onclick="javascript:history.back(); return false;">отмена</a>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

directory/templates/directory/category_update.html
{% extends 'directory/base.html' %}
{% load staticfiles %}

{% load crispy_forms_tags %}

{% block menu %}
    {% include 'directory/includes/inc_menu.html' %}
{% endblock menu %}

{% block content %}
    <div class="directory__form">
        <form class="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% for field in form %}
                <div class="form-group">
                    {{ field.label }}
                    {{ field }}
                </div>

                {% if field.errors %}
                    <div class="alert  alert-danger">
                        {{ field.errors }}
                    </div>
                {% endif %}
            {% endfor %}
            <div class="new_category_form--btn">
                <input class="form-control  bg-success  text-white  new_category_form--save" type="submit" value="сохранить">
            </div>
        </form>
        <div class="new_category_form--back_back">
            <a class="form-control  btn  btn-outline-secondary mt-3" onclick="javascript:history.back(); return false;" role="button">к списку категорий</a>
        </div>
    </div>
{% endblock content %}

directory/templates/directory/city_update.html
{% extends 'directory/base.html' %}
{% load staticfiles %}

{% load crispy_forms_tags %}

{% block menu %}
    {% include 'directory/includes/inc_menu.html' %}
{% endblock menu %}

{% block content %}
    <div class="directory__form">
        <form class="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% for field in form %}
                <div class="form-group">
                    {{ field.label }}
                    {{ field }}
                </div>

                {% if field.errors %}
                    <div class="alert  alert-danger">
                        {{ field.errors }}
                    </div>
                {% endif %}
            {% endfor %}
            <div class="new_category_form--btn">
                <input class="form-control  bg-success  text-white  new_category_form--save" type="submit" value="сохранить">
            </div>
        </form>
        <div class="new_category_form--back_back">
            <a class="form-control  btn  btn-outline-secondary mt-3" onclick="javascript:history.back(); return false;" role="button">к списку городов</a>
        </div>
    </div>
{% endblock content %}

directory/templates/directory/house.html
{% extends 'directory/base.html' %}
{% load staticfiles %}

{% load crispy_forms_tags %}

{% block menu %}
    {% include 'directory/includes/inc_menu.html' %}
{% endblock menu %}

{% block content %}
    <div class="row  mt-5  mb-3  d-flex justify-content-between">
        <h4 class="col">Дома по <span class="text-700">{{ street }}</span></h4>
        <div class="form-group">
            <a href="{% url 'directory:house_create' street.pk %}" class="btn btn-outline-primary btn-sm" role="button">Добавить дом</a>
            <a class="btn  btn-outline-secondary btn-sm" onclick="javascript:history.back(); return false;" role="button">Назад</a>
        </div>
        
    </div>
    <div class="manager-area__counters-history  mb-5">
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">ID</th>
                    <th class="text-left" scope="col">Дом №</th>
                    <th scope="col">Квартиры</th>
                    <th scope="col">Редактировать</th>
                    <th scope="col">удалиь</th>
                </tr>
            </thead>

            {% for house in house %}
            <tbody>
                <tr>
                    <td>{{ house.id }}</td>
                    <td class="text-left">Дом №{{ house.number }}, к.{{ house.add_number }}</td>
                    <td><a href="{% url 'directory:appartaments' house.pk %}" type="button" class="btn btn-outline-primary btn-sm" role="button">Квартиры</td>
                    <td><a href="{% url 'directory:house_update' house.pk %}" type="button" class="btn btn-outline-warning btn-sm" role="button">Редактировать</a></td>
                    <td><a href="{% url 'directory:house_delete' house.pk %}" class="text-danger text-decoration-none">удалить</a></td>
                </tr>
            </tbody>
            {% endfor %}

        </table> 
    </div>
{% endblock %}

directory/templates/directory/house_delete.html
{% extends 'directory/base.html' %}
{% load staticfiles %}

{% block menu %}
    {% include 'directory/includes/inc_menu.html' %}
{% endblock menu %}

{% block content %}
    <div class="directory__form">
        <p class="category_delete--text">Уверены, что хотите удалить <strong>дом № {{ object.number }} (г.{{ object.street.city }}, ул.{{ object.street }})</strong>?</p> 
        <div class="category__form">
            <form action="{% url 'directory:house_delete' object.pk %}" method="post">
                {% csrf_token %}

                <div class="form-group  d-flex  justify-content-around  mt-5">
                    <input class="btn  btn-danger" type="submit" value="удалить">
                    <a class="btn  btn-success" role="button" onclick="javascript:history.back(); return false;">отмена</a>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

directory/templates/directory/residents_delete.html
{% extends 'directory/base.html' %}
{% load staticfiles %}

{% block menu %}
    {% include 'directory/includes/inc_menu.html' %}
{% endblock menu %}

{% block content %}
    <div class="directory__form">
        <p class="category_delete--text">Уверены, что хотите удалить <strong>жильца {{ object.name }} ({{ object.personal_account }})</strong>?</p> 
        <div class="category__form">
            <form action="{% url 'directory:residents_delete' object.pk %}" method="post">
                {% csrf_token %}

                <div class="form-group  d-flex  justify-content-around  mt-5">
                    <input class="btn  btn-danger" type="submit" value="удалить">
                    <a class="btn  btn-success" role="button" onclick="javascript:history.back(); return false;">отмена</a>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

directory/templates/directory/services.html
{% extends 'directory/base.html' %}
{% load staticfiles %}

{% load crispy_forms_tags %}

{% block menu %}
    {% include 'directory/includes/inc_menu.html' %}
{% endblock menu %}

{% block content %}
    <div class="row  mt-5  mb-3  d-flex justify-content-between">
        <h4 class="col">Тарифы:  <span class="text-700">{{ category.name }}</span></h4>
        <div class="form-group">
            <a href="{% url 'directory:services_create' category.pk %}" class="btn btn-outline-primary btn-sm" role="button">добавить тариф</a>
            <a href="{% url 'directory:list' %}" class="btn  btn-outline-secondary btn-sm" role="button">назад</a>
        </div>
        
    </div>
    <div class="manager-area__counters-history  mb-5">
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">ID</th>
                    <th scope="col">Наименование</th>
                    <th scope="col">Ед.изм</th>
                    <th scope="col">Тариф</th>
                    <th scope="col">Коэфициент</th>
                    <th scope="col">Константа</th>
                    <th scope="col">Редактировать</th>
                    <th scope="col">удалиь</th>
                </tr>
            </thead>

            {% for item in services %}
                <!-- TODO отображать активные но внизу и серые -->
                {% if item.is_active %}
                    <tbody>
                        <tr>
                            <td>{{ item.id }}</td>
                            <td>{{ item.name }}</td>
                            <td>{{ item.unit }}</td>
                            <td class="text-left">{{ item.rate }}</td>
                            <td>{{ item.factor }}</td>
                            <td class="text-700">{% if item.const %} Да {% else %} Нет {% endif %}</td>
                            <td><a href="{% url 'directory:services_update' item.pk %}" type="button" class="btn btn-outline-warning btn-sm" role="button">Редактировать</a></td>
                            <td><a href="{% url 'directory:services_delete' item.pk %}" class="text-danger text-decoration-none">удалить</a></td>
                        </tr>
                    </tbody>
                {% endif %}
            {% endfor %}

        </table> 
    </div>
{% endblock %}

directory/templates/directory/services_delete.html
{% extends 'directory/base.html' %}
{% load staticfiles %}

{% block menu %}
    {% include 'directory/includes/inc_menu.html' %}
{% endblock menu %}

{% block content %}
    <div class="directory__form">
        <p class="category_delete--text">Уверены, что хотите удалить тариф <strong>{{ object.name }} ({{ object.category.name }})</strong>?</p> 
        <div class="category__form">
            <form action="{% url 'directory:services_delete' object.pk %}" method="post">
                {% csrf_token %}

                <div class="form-group  d-flex  justify-content-around  mt-5">
                    <input class="btn  btn-danger" type="submit" value="удалить">
                    <a class="btn  btn-success" role="button" onclick="javascript:history.back(); return false;">отмена</a>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

directory/templates/directory/services_update.html
{% extends 'directory/base.html' %}
{% load staticfiles %}

{% load crispy_forms_tags %}

{% block menu %}
    {% include 'directory/includes/inc_menu.html' %}
{% endblock menu %}

{% block content %}
    <form class="directory__form" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% for field in form %}
            <div class="form-group">
                {{ field.label }}
                {{ field }}
            </div>

            {% if field.errors %}
                <div class="alert  alert-danger">
                    {{ field.errors }}
                </div>
            {% endif %}
        {% endfor %}
        <div class="new_category_form--btn">
            <input class="form-control  bg-success  text-white  new_category_form--save" type="submit" value="сохранить">
        </div>
    </form>
    <div class="new_category_form--back_back">
        <a class="form-control  btn  btn-outline-secondary mt-3" onclick="javascript:history.back(); return false;" role="button">к списку тарифов</a>
    </div>
{% endblock content %}

directory/templates/directory/street_delete.html
{% extends 'directory/base.html' %}
{% load staticfiles %}

{% block menu %}
    {% include 'directory/includes/inc_menu.html' %}
{% endblock menu %}

{% block content %}
        <div class="directory__form">
            <p class="category_delete--text">Уверены, что хотите удалить улицу <strong>{{ object.street }} (г.{{ object.city }})</strong>?</p> 
            <div class="category__form">
                <form action="{% url 'directory:category_delete' object.pk %}" method="post">
                    {% csrf_token %}

                    <div class="form-group  d-flex  justify-content-around  mt-5">
                        <input class="btn  btn-danger" type="submit" value="удалить">
                        <a class="btn  btn-success" role="button" onclick="javascript:history.back(); return false;">отмена</a>
                    </div>
                </form>
            </div>
        </div>
{% endblock %}

directory/templates/directory/street_update.html
{% extends 'directory/base.html' %}
{% load staticfiles %}

{% load crispy_forms_tags %}

{% block menu %}
    {% include 'directory/includes/inc_menu.html' %}
{% endblock menu %}

{% block content %}
    <div class="directory__form">
        <form class="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% for field in form %}
                <div class="form-group">
                    {{ field.label }}
                    {{ field }}
                </div>

                {% if field.errors %}
                    <div class="alert  alert-danger">
                        {{ field.errors }}
                    </div>
                {% endif %}
            {% endfor %}
            <div class="new_category_form--btn">
                <input class="form-control  bg-success  text-white  new_category_form--save" type="submit" value="сохранить">
            </div>
        </form>
        <div class="new_category_form--back_back">
            <a class="form-control  btn  btn-outline-secondary mt-3" onclick="javascript:history.back(); return false;" role="button">к списку улиц</a>
        </div>
    </div>
{% endblock content %}