invoice/urls.py
from django.conf import settings
from django.urls import re_path, path
import invoice.views as invoice
from invoice.apps import InvoiceConfig

app_name = InvoiceConfig.name

urlpatterns = [
    re_path(r"^$", invoice.InvoiceViews.as_view(), name="invoice"),
    # path('invoice/', invoice.main, name='invoice'),
]

if settings.DEBUG:
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns
    urlpatterns += staticfiles_urlpatterns()

newcity/urls.py
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path

import mainapp.views as mainapp

urlpatterns = [
    path("", mainapp.main, name="main"),
    path("auth/", include("authnapp.urls", namespace="auth")),
    path("person/", include("personalacc.urls", namespace="person")),
    path("directory/", include("directory.urls", namespace="directory")),
    path("invoice/", include("invoice.urls", namespace="invoice")),
    path("admin/", admin.site.urls, name="admin"),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

personalacc/urls.py
from django.conf.urls import url
from django.urls import re_path

import personalacc.views as personalacc
from personalacc.apps import PersonalaccConfig

app_name = PersonalaccConfig.name

urlpatterns = [
    re_path(r"^user/$", personalacc.UserPageCreate.as_view(), name="user"),

    re_path(r"^manager/dal_user/$", personalacc.UserAutocomplete.as_view(), name="dal_user"),
    re_path(r"^manager/$", personalacc.ManagerPageCreate.as_view(), name="manager"),
    re_path(r"^manager/house_history/$", personalacc.HouseHistoryListView.as_view(), name="house_history"),
    re_path(r"^manager/recalc_history/$", personalacc.RecalcHistoryListView.as_view(), name="recalc_history"),
    re_path(r"^manager/receivable/$", personalacc.AccountsReceivableListView.as_view(), name="receivable"),

]

personalacc/models.py
from django.db import models

# Create your models here.

personalacc/forms.py
from django.forms import widgets
from authnapp.models import User
from crispy_forms.helper import FormHelper
from django import forms
from dal import autocomplete

from authnapp.forms import BootstrapStylesMixins
from mainapp.models import CurrentCounter, HouseCurrent, HouseHistory, MainBook, Payment, Privileges, Recalculations, Services, Subsidies

class MultipleForm(forms.Form):
    """Добавляем клас Мульти формности, идентификация форм будет по скрытому полю action"""
    action = forms.CharField(max_length=60, widget=forms.HiddenInput())


class CurrentCounterForm(forms.ModelForm):
    class Meta:
        model = CurrentCounter
        exclude = ("period", "electric_day", "electric_night", "electric_single", "created", "updated")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # self.fields['user'].queryset = User.objects.filter(id=kwargs['initial']['user'])
        self.fields['user'].queryset = User.objects.filter(id=kwargs['initial']['user'])
        for field_name, field in self.fields.items():
            field.widget.attrs["class"] = "form-control"
        self.helper = FormHelper()
        self.helper.form_show_labels = False


class HomeCurrentCounterForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs["class"] = "form-control"
        self.helper = FormHelper()
        self.helper.form_show_labels = False

    class Meta:
        model = HouseCurrent
        exclude = ("electric_day", "electric_night", "period", "created", "updated")


class HomeHistoryCounterForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs["class"] = "form-control"
        self.helper = FormHelper()
        # self.helper.form_show_labels = False

    class Meta:
        model = HouseHistory
        exclude = ("period", "created", "updated")


class RecalculationsForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        #Отправляем фильтрованные данные в форму
        self.fields['service'].queryset = Services.objects.filter(const=False)
        for field_name, field in self.fields.items():
            field.widget.attrs["class"] = "form-control"
        self.helper = FormHelper()
        self.helper.form_show_labels = False

    class Meta:
        model = Recalculations
        exclude = ("period", "created", "updated")
        widgets = {
            "user": autocomplete.ModelSelect2(
                url="dal_user/",
                attrs={
                    "class": "form-control",
                    "data-pleaceholder": "Начните набирать имя жильца...",
                    "data-minimum-input-length": 3,
                },
            )
        }


class SubsidiesForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['service'].queryset = Services.objects.filter(const=False)
        self.fields['user'].queryset = User.objects.none()
        self.helper = FormHelper()
        self.helper.form_show_labels = False

    class Meta:
        model = Subsidies
        exclude = ("created", "updated")
        widgets = {
        "user": autocomplete.ModelSelect2(
            url="dal_user/",
            attrs={
                "class": "form-control",
                "data-pleaceholder": "Начните набирать имя жильца...",
                "data-minimum-input-length": 3,
                },
            )
        }


class PrivilegesForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['service'].queryset = Services.objects.filter(const=False)
        self.fields['user'].queryset = User.objects.none()
        self.helper = FormHelper()
        self.helper.form_show_labels = False

    class Meta:
        model = Privileges
        exclude = ("is_active", "created", "updated")
        widgets = {
            "user": autocomplete.ModelSelect2(
                url="dal_user/",
                attrs={
                    "class": "form-control",
                    "data-pleaceholder": "Начните набирать имя жильца...",
                    "data-minimum-input-length": 3,
                },
            )
        }


class PaymentsForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['direction'].queryset = MainBook.objects.all().filter(direction="D")
        self.fields['user'].queryset = User.objects.none()
        self.helper = FormHelper()
        self.helper.form_show_labels = False

    class Meta:
        model = MainBook
        exclude = ("created", "updated")
        widgets = {
            "user": autocomplete.ModelSelect2(
                url="dal_user/",
                attrs={
                    "class": "form-control",
                    "data-pleaceholder": "Начните набирать имя жильца...",
                    "data-minimum-input-length": 3,
                },
            )
        }

    

personalacc/views.py
import datetime
import json
from typing import KeysView
from dal import autocomplete

from django.contrib.auth.mixins import LoginRequiredMixin
from django.core import serializers
from django.http import JsonResponse
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, DeleteView, ListView, UpdateView

from authnapp.models import User
from mainapp.models import (
    CurrentCounter,
    MainBook,
    Payment,
    PersonalAccountStatus,
    UK,
    Appartament,
    HistoryCounter,
    HouseCurrent,
    HouseHistory,
    Privileges,
    Recalculations,
    Subsidies,
    UserProfile,
)
from personalacc.forms import (
    CurrentCounterForm, 
    HomeCurrentCounterForm, 
    HomeHistoryCounterForm, 
    RecalculationsForm, 
    SubsidiesForm,
    PrivilegesForm,
    PaymentsForm
    )


class UserPageCreate(LoginRequiredMixin, CreateView):
    model = User
    form_class = CurrentCounterForm
    context_object_name = "user"
    template_name = "personalacc/user_list.html"
    success_url = reverse_lazy("person:thanks")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["profiles"] = UserProfile.objects.get(user=self.request.user)
        context["payments"] = MainBook.objects.filter(direction="C")
        context["appartament"] = Appartament.objects.filter(user=self.request.user)
        context["history"] = HistoryCounter.get_last_val(self.request.user)
        context["title"] = "Пользователь | ООО Новый город"
        return context
    
    def get_form_kwargs(self, *args, **kwargs):
        kwargs = super().get_form_kwargs(*args, **kwargs)
        #Заполняем форму начальными данными
        kwargs['initial'] = {'user': self.request.user.id}
        return kwargs
    
    def get_queryset(self):
        qs = super().get_queryset()
        return qs.get(pk=self.request.user.id)

    def post(self, request, *args, **kwargs):
        if self.request.is_ajax and self.request.method == "POST":
            if self.request.POST.get("form_type") == "counterForm":
                data = self.get_form_kwargs()
                form = self.form_class(self.request.POST, initial=data['initial'])
        
            if form.is_valid():
                post = self.request.POST
                user = self.request.user
                # period = datetime.datetime.now().date().replace(day=1)
                #TODO для проверки работы скрипта
                period = datetime.datetime.now().date().replace(day=1, month=10)
                update_values = {
                    "col_water": post.get("col_water"),
                    "hot_water": post.get("hot_water"),
                    #TODO электричество пока отменяется
                    # "electric_day": post.get("electric_day"),
                    # "electric_night": post.get("electric_night"),
                }
                obj, created = CurrentCounter.objects.update_or_create(
                    user=user, period=period, defaults=update_values
                )
                # При создании новой записи удаляем старую
                if created:
                    previous_month = (period - datetime.timedelta(days=1)).replace(day=1)
                    previous_value = CurrentCounter.objects.filter(user=user, period=previous_month)
                    previous_value.delete()
                data = serializers.serialize("json", [obj,],)
                return JsonResponse({"instance": data}, status=200)
            else:
                return JsonResponse({"error": form.errors}, status=400)
        return JsonResponse({"error": ""}, status=400)


class ManagerPageCreate(LoginRequiredMixin, CreateView):
    form_class = HomeCurrentCounterForm
    form_classes = {
        "house_count_form": HomeCurrentCounterForm,
        "house_history_form": HomeHistoryCounterForm,
        "recalculations_form": RecalculationsForm,
        "privilege_form": PrivilegesForm,
        "subsidies_form": SubsidiesForm,
        "payments_form": PaymentsForm
        }
    template_name = "personalacc/manager_list.html"
    success_url = reverse_lazy("person:manager")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        for name, form in self.form_classes.items():
            if name not in context:
                context[name] = form()
        context["uk"] = UK.objects.all()
        context["house_history"] = HouseHistory.objects.all()
        context["house_current"] = HouseCurrent.objects.all()
        context["house_rec"] = Recalculations.objects.all()
        context["house_privileges"] = Privileges.objects.all()
        context["house_subsidies"] = Subsidies.objects.all()
        context["house_pay_debit"] = MainBook.get_all_debit()
        context["title"] = "Менеджер | ООО Новый город"
        return context

    def post(self, *args, **kwargs):
        post = self.request.POST
        user = self.request.POST.get("user")
        #TODO для проверки работы скрипта
        # period = datetime.datetime.now().date().replace(day=1, month=7)
        period = datetime.datetime.now().date().replace(day=1)
        handle = {
            "house_count_form": self.house_count_process,
            "recalculations_form": self.recalculations_process,
            "privilege_form": self.privilege_process,
            "subsidies_form": self.subsidies_process,
            "payments_form": self.payments_process
            }
        if self.request.is_ajax and self.request.method == "POST":
            type_form = post.get("form_type")
            for cls, el in self.form_classes.items():
                if type_form == cls:
                    form = el(post)
                    if form.is_valid():
                        func = handle[cls]
                        ser_instance = func(self, form=form, post=post, user=user, period=period)
                        return JsonResponse({"instance": ser_instance}, status=200)
                    else:
                        return JsonResponse({"error": form.errors}, status=400)
        return JsonResponse({"error": ""}, status=400)

    def house_count_process(self, *args, **kwargs):
        house = kwargs['post'].get("house")
        update_values = {
            "col_water": kwargs['post'].get("col_water"),
            "hot_water": kwargs['post'].get("hot_water"),
            #TODO электричество пока отменяется
            # "electric_day": post.get("electric_day"),
            # "electric_night": post.get("electric_night"),
        }
        obj, created = HouseCurrent.objects.update_or_create(
            house_id=house, period=kwargs['period'], defaults=update_values
        )
        # При создании новой записи удаляем старую
        if created:
            previous_month = (kwargs['period'] - datetime.timedelta(days=1)).replace(day=1)
            previous_value = HouseCurrent.objects.filter(house_id=house, period=previous_month)
            previous_value.delete()
        ser_instance = serializers.serialize("json", [obj,],)
        return ser_instance

    def recalculations_process(self, *args, **kwargs):
        update_values = {
            "recalc": kwargs['post'].get("recalc"),
            "desc": kwargs['post'].get("desc")
        }
        obj, created = Recalculations.objects.update_or_create(
            user_id=kwargs['user'], period=kwargs['period'], service_id=kwargs['post'].get("service"), defaults=update_values
        )
        ser_instance = serializers.serialize("json", [obj,],)
        return ser_instance
      
    def privilege_process(self, *args, **kwargs):
        update_values = {
            "sale": kwargs['post'].get("sale"),
            "desc": kwargs['post'].get('desc')
        }
        obj, created = Privileges.objects.update_or_create(
            user_id=kwargs['user'], service_id=kwargs['post'].get("service"), defaults=update_values
        )
        ser_instance = serializers.serialize("json", [obj,],)
        return ser_instance

    def subsidies_process(self, *args, **kwargs):
        update_values = {
            "sale": kwargs['post'].get("sale"),
            "desc": kwargs['post'].get('desc')
        }
        obj, created = Subsidies.objects.update_or_create(
            user_id=kwargs['user'], service_id=kwargs['post'].get("service"), defaults=update_values
        )
        ser_instance = serializers.serialize("json", [obj,],)
        return ser_instance

    def payments_process(self, *args, **kwargs):
        update_values = {
            "direction": kwargs['post'].get("direction"),
            "amount": kwargs['post'].get("amount")
        }
        obj, created = MainBook.objects.update_or_create(
            user_id=kwargs["user"], period=kwargs["period"], defaults=update_values
        )
        ser_instance = serializers.serialize("json", [obj,],)
        return ser_instance


class HouseHistoryListView(LoginRequiredMixin, ListView):
    model = HouseHistory
    context_object_name = "history"
    template_name = "personalacc/house_history_list.html"


class RecalcHistoryListView(LoginRequiredMixin, ListView):
    model = Recalculations
    context_object_name = "recalc"
    template_name = "personalacc/recalc_history_list.html"


class AccountsReceivableListView(LoginRequiredMixin, ListView):
    model = PersonalAccountStatus
    context_object_name = "receivable"
    template_name = "personalacc/accounts_receivable.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Дебиторская задолжность | ООО Новый город"
        context["appartament"] = Appartament.objects.all()
        return context


class UserAutocomplete(autocomplete.Select2QuerySetView):
    def get_queryset(self):
        # Don't forget to filter out results depending on the visitor!
        if not self.request.user.is_authenticated:
            return User.objects.none()

personalacc/templates/personalacc/accounts_receivable.html
{% extends 'personalacc/base.html' %}
{% load staticfiles %}


{% block menu %}
    {% include 'mainapp/includes/inc_menu.html' %}
{% endblock menu %}

{% block content %}

<div class="container">
    <div class="my-5">
        <div class="row  mt-5  mb-3  d-flex justify-content-between">
            <h4 class="col">Информация по задолжности</h4>
            <a href="{% url 'personalacc:manager' %}" class="col  text-right  text-decoration-none">На главную</a>
        </div>
        <div class="manager-area__counters-history  mb-5">
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Жилец</th>
                        <th scope="col">Адрес</th>
                        <th scope="col">Задолжность</th>
                    </tr>
                </thead>
    
                {% for el in receivable %}
                <tbody>
                    <tr>
                        <td>{{ el.id }}</td>
                        <td>{{ el.user }}</td>
                        {% for app in appartament %}
                            {% if app.user == el.user %}
                                <td>{{ app }}</td>
                            {% endif %}
                        {% endfor %}
                        <td>{{ el.amount }}</td>
                    </tr>
                </tbody>
                {% endfor %}
    
            </table> 
        </div>
    </div>
</div>

{% endblock content %}

personalacc/templates/personalacc/user_list.html
{% extends 'personalacc/base.html' %}
{% load staticfiles %}

{% load crispy_forms_tags %}


{% block menu %}
    {% include 'mainapp/includes/inc_menu.html' %}
{% endblock menu %}

{% block content %}
<div class="intro-user  mt-5">
    <div class="container">
        <h2 class="intro-user__title  text-center">Здравствуйте, Иванов Иван!</h2>
    </div>
</div>

<div class="user-area">
    <div class="container">

        <h4 class="user-area__title  mt-3  mb-3">Личный кабинет</h4>

    </div>
</div>

<div class="tenants">
    <div class="container">
        <div class="d-flex  flex-row  tenants__item  flex-column">

            <!-- Nav-TABS -->
            <ul class="nav nav-tabs  mb-5" id="myTab" role="tablist">
                <li class="nav-item" role="presentation">
                    <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab"
                        aria-controls="home" aria-selected="true">Общая информация</a>
                </li>
                <li class="nav-item" role="presentation">
                    <a class="nav-link" id="profile-tab" data-toggle="tab" href="#testimony" role="tab"
                        aria-controls="profile" aria-selected="false">Подать показания</a>
                </li>
                <li class="nav-item" role="presentation">
                    <a class="nav-link" id="contact-tab" data-toggle="tab" href="#history" role="tab"
                        aria-controls="contact" aria-selected="false">История платежей</a>
                </li>
            </ul>

            <!-- Tabs-CONTENT -->
            <div class="tab-content  pb-5  mb-5" id="myTabContent">

                <!-- Tab-HOME -->
                <div class="tab-pane  fade  show  active  user-area__table" id="home" role="tabpanel" aria-labelledby="home-tab">
                    
                    <p class="user-area__subtitle  text-700  mb-4">Ваши персональные данные</p>
                    <table class="table table-striped">
                        {% if user.is_active %}
                        <tbody>
                            <tr>
                                <th scope="row">ФИО</th>
                                <td>{{ user.name }}</td>
                            </tr>
                            <tr>
                                <th scope="row">Лицевой счет</th>
                                <td>{{ user.personal_account }}</td>
                            </tr>
                            <tr>
                                <th scope="row">E-mail</th>
                                <td>{{ user.email }}</td>
                            </tr>
                            <tr>
                                <th scope="row">Телефон</th>
                                <td>{{ user.phone }}</td>
                            </tr>
                            <tr>
                                <th scope="row">Город</th>
                                <td>{{ appartament.0.house.city.city }}</td>
                            </tr>
                            <tr>
                                <th scope="row">Адрес</th>
                                <td>
                                    {{ appartament.0 }}
                                </td>
                            </tr>
                        </tbody>
                        {% endif %}
                    </table>
                </div>

                <!-- Tab-COUNTER -->
                <div class="tab-pane  fade  user-area__table" id="testimony" role="tabpanel" aria-labelledby="profile-tab">
                    <h4 class="mb-3">Введите показания счетчиков в поля</h4>
                        <div class="alert alert-warning" role="alert">
                            <ul class="">
                                {% comment 'Заказчик отменил пока'%}
                                    <li><span class="text-700">Счетчик ГВС</span> (горячая вода), укажите целое число до запятой</li>
                                    <li><span class="text-700">Счетчик ХВС</span> (холодная вода), укажите целое число до запятой</li>
                                {% endcomment %}
                                {% if user.profiles.type_electric_meter == '2' %}
                                    <li><span class="text-700">Электроэнергия (день)</span>, укажите целое число до запятой</li>
                                    <li><span class="text-700">Электроэнергия (ночь)</span>, укажите целое число до запятой</li>
                                {% else %}
                                    <li><span class="text-700">Электроэнергия</span>, укажите целое число до запятой</li>
                                {% endif %}
                                <li>Нажать кнопку <span class="text-700">СОХРАНИТЬ</span></li>
                            </ul>
                        </div>

                    {% now "d" as today %}
                    {% if "01" < today and today < "31" %}
                        <h4 class="mt-5">Таблица для заполнения</h4>
                        <div class="">
                            <form id="counterForm" method="POST" name="counterForm">
                                {% csrf_token %}
                                <input type="hidden" name="form_type" value="counterForm">
        
                                <div class="user-area__table">
                                    <table class="user-area__table  table">
                                        <thead>
                                            <tr>
                                                <th scope="col"></th>
                                                <th class="text-center" scope="col">Показания</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <th scope="row" type>Пользователь:</th>
                                                <td class="text-center" id="userName">{{ form.user|as_crispy_field }}</td>
                                            </tr>
                                            <tr>
                                                <th scope="row">Холодная вода:</th>
                                                <td class="text-center" id="electricDay">{{ form.col_water|as_crispy_field }}</td>
                                            </tr>
                                            <tr>
                                                <th scope="row">Горячая вода:</th>
                                                <td class="text-center" id="electricNight">{{ form.hot_water|as_crispy_field }}</td>
                                            </tr>
                                            {% comment 'Электроэнергию не считаем'%}
                                                {% if user.profiles.type_electric_meter == '2' %}
                                                <tr>
                                                    <th scope="row">Электроэнергия день:</th>
                                                    <td class="text-center" id="electricDay">{{ form.electric_day|as_crispy_field }}</td>
                                                </tr>
                                                <tr>
                                                    <th scope="row">Электроэнергия ночь:</th>
                                                    <td class="text-center" id="electricNight">{{ form.electric_night|as_crispy_field }}</td>
                                                </tr>
                                                {% elif user.profiles.type_electric_meter == '1'  %}
                                                <tr>
                                                    <th scope="row">Электроэнергия:</th>
                                                    <td class="text-center" id="electricSingle">{{ form.electric_single|as_crispy_field }}</td>
                                                </tr>
                                                {% endif %}
                                                {% if user.profiles.type_electric_meter == '2' %}
                                                <tr>
                                                    <th scope="row">Электроэнергия день:</th>
                                                    <td class="text-center" id="electricDay">{{ form.electric_day|as_crispy_field }}</td>
                                                </tr>
                                                <tr>
                                                    <th scope="row">Электроэнергия ночь:</th>
                                                    <td class="text-center" id="electricNight">{{ form.electric_night|as_crispy_field }}</td>
                                                </tr>
                                                {% elif user.profiles.type_electric_meter == '1'  %}
                                                <tr>
                                                    <th scope="row">Электроэнергия:</th>
                                                    <td class="text-center" id="electricSingle">{{ form.electric_single|as_crispy_field }}</td>
                                                </tr>
                                                {% endif %}
                                            {% endcomment %}
                                        </tbody>
                                    </table>
                                </div>
                                <button action="{% url 'person:user' %}" type="button" class="form-control  bg-success  text-white  new_category_form--save" id="counterBtn">Сохранить</button>
                            </form>
                        </div>
                    {% else %}
                        <div class="alert alert-danger" role="alert">
                            ВНИМАНИЕ! Показания принимаются с 20 по 26 число каждого месяца!
                        </div>
                    {% endif %}
                </div>

                <!-- Tab-HISTORY -->
                <div class="tab-pane fade" id="history" role="tabpanel" aria-labelledby="contact-tab">
                    <h4 class="mb-3">История начислений</h4>
                    <div class="user-area__history-tab">
                        <table class="table">
                            <thead class="thead-light">
                                <tr>
                                    <th scope="col">Месяц</th>
                                    <th class="text-center" scope="col">Сумма</th>
                                    <th class="text-center" scope="col">Квитанция</th>
                                    <th class="text-center" scope="col">Оплатить</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td>01.2021</td>
                                    <td class="text-center">4500 руб.</td>
                                    <td class="text-center"><a class="btn btn-light border border-secondary  btn-sm" href="{% url 'invoice:invoice' %}" role="button">Квитанция</a></td>
                                    <!-- <td class="text-center"><button type="submit" href="{% url 'invoice:invoice' %}" class="btn btn-light border border-secondary  btn-sm">Квитанция</button></td> -->
                                    <td class="text-center"><a href="#" class="text-decoration-none">Оплатить</a></td>
                                </tr>
                                <tr>
                                    <td>02.2021</td>
                                    <td class="text-center">4200 руб.</td>
                                    <td class="text-center"><button type="button" class="btn btn-light border border-secondary  btn-sm">Квитанция</button></td>
                                    <td class="text-center"><a href="#" class="text-decoration-none">Оплатить</a></td>
                                </tr>
                                <tr>
                                    <td>03.2021</td>
                                    <td class="text-center">5100 руб.</td>
                                    <td class="text-center"><button type="button" class="btn btn-light border border-secondary  btn-sm">Квитанция</button></td>
                                    <td class="text-center"><a href="#" class="text-decoration-none">Оплатить</a></td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}