authnapp/urls.py
from django.contrib.auth.views import (
    PasswordChangeDoneView,
    PasswordChangeView,
    PasswordResetCompleteView,
    PasswordResetConfirmView,
    PasswordResetDoneView,
    PasswordResetView,
)
from django.urls import re_path
from django.urls.base import reverse, reverse_lazy

import authnapp.views as authnapp
from authnapp.apps import AuthnappConfig
from authnapp.views import ProfileUpdateView

from .forms import MyPassResetForm, MyPassSetForm, MyPasswordChangeForm

app_name = AuthnappConfig.name

urlpatterns = [
    re_path(r"^login/$", authnapp.login, name="login"),
    re_path(r"^logout/$", authnapp.logout, name="logout"),
    re_path(r"^register/$", authnapp.register, name="register"),
    re_path(r"^edit/(?P<pk>\d+)/$", ProfileUpdateView.as_view(), name="edit"),
    # re_path(r"^edit/$", authnapp.edit, name="edit"),
    re_path(r"^verify/(?P<email>.+)/(?P<activation_key>\w+)/$", authnapp.verify, name="verify"),
    # change password urls
    re_path(
        r"^password-change/$",
        PasswordChangeView.as_view(
            template_name="authnapp/password_change.html",
            success_url=reverse_lazy("auth:password_change_done"),
            form_class=MyPasswordChangeForm,
        ),
        name="password_change",
    ),
    re_path(
        r"^password-change/done/$",
        PasswordChangeDoneView.as_view(
            template_name="authnapp/password_change_done.html",
        ),
        name="password_change_done",
    ),
    # reset password urls
    re_path(
        r"^password-reset/$",
        PasswordResetView.as_view(
            template_name="authnapp/password_reset.html",
            email_template_name="authnapp/password_reset_email.html",
            success_url=reverse_lazy("auth:password_reset_done"),
            form_class=MyPassResetForm,
        ),
        name="password_reset",
    ),
    re_path(
        r"^password-reset/done/$",
        PasswordResetDoneView.as_view(
            template_name="authnapp/password_reset_done.html",
        ),
        name="password_reset_done",
    ),
    re_path(
        r"^password-reset/confirm/(?P<uidb64>[-\w]+)/(?P<token>[-\w]+)/$",
        PasswordResetConfirmView.as_view(
            template_name="authnapp/password_reset_confirm.html",
            success_url=reverse_lazy("auth:password_reset_complete"),
            form_class=MyPassSetForm,
        ),
        name="password_reset_confirm",
    ),
    re_path(
        r"^password-reset/complete/$",
        PasswordResetCompleteView.as_view(
            template_name="authnapp/password_reset_complete.html",
        ),
        name="password_reset_complete",
    ),
]

invoice/urls.py
from django.conf import settings
from django.urls import re_path, path
import invoice.views as invoice
from invoice.apps import InvoiceConfig

app_name = InvoiceConfig.name

urlpatterns = [
    re_path(r"^$", invoice.InvoiceViews.as_view(), name="invoice"),
    # path('invoice/', invoice.main, name='invoice'),
]

if settings.DEBUG:
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns
    urlpatterns += staticfiles_urlpatterns()

newcity/urls.py
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path

import mainapp.views as mainapp

urlpatterns = [
    path("", mainapp.main, name="main"),
    path("auth/", include("authnapp.urls", namespace="auth")),
    path("person/", include("personalacc.urls", namespace="person")),
    path("directory/", include("directory.urls", namespace="directory")),
    path("invoice/", include("invoice.urls", namespace="invoice")),
    path("admin/", admin.site.urls, name="admin"),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

authnapp/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from datetime import timedelta

from django.contrib.auth.base_user import AbstractBaseUser
from django.contrib.auth.models import Group, PermissionsMixin
from django.core.mail import send_mail
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils.timezone import now
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import Group


from .managers import UserManager


class User(AbstractBaseUser, PermissionsMixin):
    is_client = models.BooleanField(default=True, verbose_name="Пользователь")
    is_staff = models.BooleanField(
        default=False, verbose_name="Менеджер", help_text="Обозначает, что этот пользователь - Администратор"
    )
    personal_account = models.CharField(
        max_length=128, help_text="Введите номер лицевого счета: 7777777", verbose_name="Лицевой счет", unique=True
    )
    password = models.CharField(verbose_name="Пароль", max_length=128)
    name = models.CharField(verbose_name="ФИО", max_length=128, null=True, blank=True, help_text="Иванов Иван Иванович")
    email = models.EmailField(
        verbose_name="Email", unique=True, null=True, blank=True, help_text="E-mail в формате - user@example.com"
    )
    phone = models.CharField(
        verbose_name="Телефон", max_length=11, null=True, blank=True, help_text="Номер телефона в формате - 79823212334"
    )
    is_active = models.BooleanField(verbose_name="Активный", default=True)
    is_superuser = models.BooleanField(
        default=False,
        verbose_name="Суперпользователь",
        help_text="Обозначает, что у этого пользователя есть все разрешения, без их явного назначения.",)

    last_login = models.DateTimeField(blank=True, null=True, verbose_name="Последний вход")

    activation_key = models.CharField(verbose_name="Ключ подтверждения", max_length=128, blank=True)
    activation_key_expires = models.DateTimeField(
        verbose_name="Актуальность ключа", default=(now() + timedelta(hours=48)))

    objects = UserManager()

    USERNAME_FIELD = "personal_account"
    REQUIRED_FIELDS = ["password", "email"]

    class Meta:
        verbose_name = _("Пользователь")
        verbose_name_plural = _("Пользователи")

    def __str__(self):
        return f"({self.personal_account}) - {self.name}"

    def get_full_name(self):
        """
        Returns the name plus the last_name plus patronymic, with a space in between.
        """
        full_name = f"{self.name}"
        return full_name.strip()

    def get_short_name(self):
        """
        Returns the short name for the user.
        """
        return self.name

    def email_user(self, subject, message, from_email=None, **kwargs):
        """
        Sends an email to this User.
        """
        send_mail(subject, message, from_email, [self.email], **kwargs)

    def is_activation_key_expired(self):
        """
        Checks if the key is up-to-date.
        """
        if now() <= self.activation_key_expires:
            return False
        else:
            return True


# Подсели на сигнал после сохранения модели
@receiver(post_save, sender=User)
def add_admin_permission(sender, instance, created, **kwargs):
    if created and not instance.is_superuser:
        if instance.is_client == True:
            # Если клиент добавляем в группу "Client"
            grupo = Group.objects.get(name="Client")
            grupo.user_set.add(instance)
        if instance.is_staff == True:
            # Если Менеджер очищаем от всех групп и добавляем в группу "Manager"
            instance.groups.clear()
            grupo = Group.objects.get(name="Manager")
            grupo.user_set.add(instance)

authnapp/views.py
from django import forms
from django.forms.formsets import formset_factory
from mainapp.models import Appartament, UserProfile
from django.conf import settings
from django.contrib import auth
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.mail import send_mail
from django.db import transaction
from django.forms.models import BaseInlineFormSet, inlineformset_factory
from django.shortcuts import HttpResponseRedirect, get_object_or_404, render
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, DeleteView, ListView, UpdateView

from authnapp.forms import (
    AppartamentEditForm,
    AppartamentFormset,
    ProfileFormset,
    UserEditForm,
    UserLoginForm,
    UserProfileEditForm,
    UserRegisterForm,
)
from authnapp.models import User


def login(request):
    title = 'Вход | УК "Новый город"'

    login_form = UserLoginForm(data=request.POST or None)
    if request.method == "POST" and login_form.is_valid():
        personal_account = request.POST["username"]
        password = request.POST["password"]

        user = auth.authenticate(personal_account=personal_account, password=password)
        if user and user.is_active:
            auth.login(request, user)
            return HttpResponseRedirect(reverse("main"))

    content = {"title": title, "form": login_form}
    return render(request, "authnapp/login.html", content)


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse("main"))


def register(request):
    title = 'Регистрация | УК "Новый город"'

    if request.method == "POST":
        register_form = UserRegisterForm(request.POST, request.FILES)

        if register_form.is_valid():
            user = register_form.save()
            if send_verify_mail(user):
                print("сообщение для подтверждения регистрации отправлено")
                return HttpResponseRedirect(reverse("auth:login"))
            print("ошибка отправки сообщения для подтверждения регистрации")
            return HttpResponseRedirect(reverse("auth:login"))
    else:
        register_form = UserRegisterForm()

    content = {"title": title, "register_form": register_form}
    return render(request, "authnapp/register.html", content)


def send_verify_mail(user):
    verify_link = reverse("auth:verify", args=[user.email, user.activation_key])

    title = f"Подтверждение учетной записи {user.personal_account}"
    message = f"Для подтверждения учетной записи {user.personal_account} \
    на портале {settings.DOMAIN_NAME} перейдите по ссылке: \
    \n{settings.DOMAIN_NAME}{verify_link}"

    print(f"from: {settings.EMAIL_HOST_USER}, to: {user.email}")
    return send_mail(
        title,
        message,
        settings.EMAIL_HOST_USER,
        [user.email],
        fail_silently=False,
    )


def verify(request, email, activation_key):
    try:
        user = User.objects.get(email=email)
        if user.activation_key == activation_key and not user.is_activation_key_expired():
            print(f"user {user} is activated")
            user.is_active = True
            user.save()
            auth.login(request, user, backend="django.contrib.auth.backends.ModelBackend")

            return render(request, "authnapp/verification.html")
        print(f"error activation user: {user}")
        return render(request, "authnapp/verification.html")

    except Exception as e:
        print(f"error activation user : {e.args}")

    return HttpResponseRedirect(reverse("main"))


class ProfileUpdateView(LoginRequiredMixin, UpdateView):
    model = User
    template_name = "authnapp/edit.html"
    success_url = reverse_lazy("main")
    form_class = UserEditForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.POST:
            context["profile_form"] = ProfileFormset(self.request.POST, instance=self.object)
        else:
            context["profile_form"] = ProfileFormset(instance=self.object)
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        formset = ProfileFormset(self.request.POST, instance=self.object)

        if not self.request.user.is_staff:
            if form.is_valid() and formset.is_valid():
                return self.form_valid(form, formset)
            return self.form_invalid(form, formset)
        else:
            if form.is_valid():
                return self.form_valid(form, formset)

    def form_valid(self, form, formset):
        if self.request.user.is_staff:
            self.object = form.save()
        else:
            with transaction.atomic():
                self.object = form.save()
                formset.instance = self.object
                formset.save()

        return HttpResponseRedirect(self.get_success_url())

    # def post(self, *args, **kwargs):
    #     if self.request.is_ajax and self.request.method == "POST":

    #         if self.request.POST.get("form_type") == 'houseCounterForm':
    #             form = self.form_class(self.request.POST)
    #         elif self.request.POST.get("form_type") == 'recalcForm':
    #             form = self.second_form_class(self.request.POST)

    #         if form.is_valid():
    #             post = self.request.POST
    #             house = post.get('house')
    #             period = datetime.datetime.now().date().replace(day=1)
    #             # period = datetime.datetime.now().date().replace(day=1, month=7)
    #             update_values = {
    #                 'col_water': post.get('col_water'),
    #                 'hot_water': post.get('hot_water'),
    #                 'electric_day': post.get('electric_day'),
    #                 'electric_night': post.get('electric_night'),
    #             }
    #             obj, created = HouseCurrent.objects.update_or_create(house_id=house, period=period, defaults=update_values)
    #             #При создании новой записи удаляем старую
    #             if created:
    #                 previous_month = (period - datetime.timedelta(days=1)).replace(day=1)
    #                 previous_value = HouseCurrent.objects.filter(house_id=house, period=previous_month)
    #                 previous_value.delete()
    #             ser_instance = serializers.serialize('json', [ obj, ])
    #             return JsonResponse({"instance": ser_instance}, status=200)
    #         else:
    #             return JsonResponse({"error": form.errors}, status=400)

    #     return JsonResponse({"error": ""}, status=400)

    # def form_valid(self, form):
    #     context = self.get_context_data()
    #     appartaments = context["appartament_form"]

    #     with transaction.atomic():
    #         self.object = form.save()
    #         if appartaments.is_valid():
    #             appartaments.instance = self.object
    #             appartaments.save()

    #     return super().form_valid(form)

    def form_invalid(self, form, formset):
        return self.render_to_response(
            self.get_context_data(
                form=form,
                appartament_form=formset,
            )
        )

authnapp/templates/authnapp/base.html
{% load staticfiles %}

<!doctype html>
<html lang="ru">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Useful meta tags -->
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="index, follow, noodp">
    <meta name="googlebot" content="index, follow">
    <meta name="google" content="notranslate">
    <meta name="format-detection" content="telephone=no">
    <meta name="keywords" content="">
    <meta name="description" content="">

    {% block css %}

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">

    <!-- Main CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    {% endblock css %}


    <!-- Главная | УК "Новый Город" -->
    <title>
        {% block title %}
        {% endblock title %}
    </title>
</head>

<body>
    <header class="header">
        <nav class="navbar navbar-expand-lg navbar-light bg-warning">
            <div class="container"> 
                <img class="mr-3" src="{% static 'img/icon/house-fill.svg' %}" alt="House" width="30" height="30">
                <a class="navbar-brand" href="/">УК Новый Город</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation"> <span class="navbar-toggler-icon"></span>
                </button>

                {% block menu %}
                {% endblock menu %}

            </div>
        </nav>
    </header>

    {% block content %}
    {% endblock content %}

    <!-- JavaScript -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0"
        crossorigin="anonymous"></script>
    <script src="{% static 'js/jquery-3.6.0.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <!-- jQuery formset section -->
    <script src="{% static 'js/jquery.formset.js' %}"></script>
    <!-- <script src="{% static 'js/user_profiles.js' %}"></script> -->
    <!-- <script src="{% static 'js/html2canvas.js' %}"></script> -->
    <!-- <script src="{% static 'js/invoice.js' %}"></script> -->
    {% block js %}
    {% endblock %}
</body>

</html>

authnapp/templates/authnapp/edit.html
{% extends 'authnapp/base.html' %}
{% load staticfiles %}

{% load auth_extras %}
{% load crispy_forms_tags %}

{% block menu %}
{% include 'authnapp/includes/inc_menu.html' %}
{% endblock menu %}

{% block content %}

<section class="edit  mt-5">
    <div class="container  d-flex  justify-content-center">
        <div class="edit__item">

            <form class="form-horizontal" action="{% url 'auth:edit' object.pk %}" method="post"
                enctype="multipart/form-data">
                {% csrf_token %}
                {% if next_page %}
                    <input type="hidden" name="next_page" value="{{ next_page }}">
                {% endif %}
                {% for field in form %}
                    <div class="form-group">
                        {{ field.label }}
                        {{ field }}
                    </div>

                    {% if field.errors %}
                        <div class="alert  alert-danger">
                            {{ field.errors }}
                        </div>
                    {% endif %}
                {% endfor %}
                {% if not user.is_staff and not user.is_superuser %}
                <table class="table">
                    {{ profile_form.management_form }}
                    {{ profile_form.non_form_errors }}
                    
                        {% for form in profile_form %}
                        <div class="list-inline">
                            {{ form.as_p }}
                        </div>
                            {% if form.errors %}
                                <div class="alert  alert-danger">
                                    {{ form.errors }}
                                </div>
                            {% endif %}
                        {% endfor %}
                </table>
                {% endif %}
                <br>

                <div class="change_pass  pb-5">
                    <a href="{% url 'authnapp:password_change' %}"
                        class="col  text-right  text-decoration-none">Изменить пароль</a>
                </div>

                <input class="btn btn-outline-primary btn-block  mb-3" type="submit" value="сохранить">

            </form>
            <a href="{% url 'main' %}" class="btn btn-outline-secondary btn-block" role="button">
                на главную
            </a>

        </div>
    </div>
</section>
{% endblock %}

{% block js %}
<script>
    $('#id_password').parent().hide();
    $('#id_personal_account').hide();
    $('#id_personal_account').before('<p style="font-weight: bold;">{{ user.personal_account }}</p>');
</script>
{% endblock %}

authnapp/templates/authnapp/login.html
{% extends 'authnapp/base.html' %}
{% load staticfiles %}


{% block menu %}
    {% include 'authnapp/includes/inc_menu.html' %}
{% endblock menu %}

{% block content %}
<section class="login">
    <div class="container  d-flex  justify-content-center">
        <div class="login__item">
            <form class="form-horizontal" action="{% url 'auth:login' %}" method="post">
                {% csrf_token %}
                {% if next_page %}
                    <input type="hidden" name="next_page" value="{{ next_page }}">
                {% endif %}
                {% if form.errors %}
                    <div class="alert  alert-danger">
                        {{ form.non_field_errors }}
                    </div>
                {% endif %}
                {% for field in form %}
                    <div class="form-group">
                        {{ field.label }}
                        {{ field }}
                    </div>
                    {% if field.errors %}
                        <div class="alert  alert-danger">
                            {{ field.errors }}
                        </div>
                    {% endif %}
                {% endfor %}
                <br>
                <a href='{% url "auth:password_reset" %}' class="text-decoration-none  text-right">Забыли пароль?</a>
                <input class="btn btn-outline-primary btn-block" type="submit" value="войти">
            </form>
        </div>
    </div>
</section>
{% endblock content %}

authnapp/templates/authnapp/password_change.html
{% extends "authnapp/base.html" %}

{% block title %}Изменение пароля{% endblock %}

{% block menu %}
    {% include 'authnapp/includes/inc_menu.html' %}
{% endblock menu %}

{% block content %}

<section class="password  mt-5">
    <div class="container  d-flex  justify-content-center">
        <div class="password__items">

            <h1 class="text-center  mb-5">Изменить пароль</h1>
            <form action="{% url 'auth:password_change' %}" method="post">
                {% csrf_token %}
                {% for error in form.non_field_errors %}
                    <div class="alert  alert-danger">
                        {{ error }}
                    </div>
                {% endfor %}

                {% for field in form %}
                    <div class="form-group">
                        {{ field.label }}
                        {{ field }}
                    </div>

                    {% if field.errors %}
                        <div class="alert  alert-danger">
                            {{ field.errors }}
                        </div>
                    {% endif %}
                {% endfor %}
                <button type="submit" class="btn btn-success">Изменить</button>

            </form>
        </div>
    </div>
</section>
{% endblock %}

authnapp/templates/authnapp/password_change_done.html
{% extends "authnapp/base.html" %}

{% block title %}Изменение пароля{% endblock %}

{% block menu %}
    {% include 'authnapp/includes/inc_menu.html' %}
{% endblock menu %}

{% block content %}

<section class="password  mt-5">
    <div class="container  d-flex  justify-content-center">
        <div class="password__items">
            <div class="mt-5  flex-column  d-flex  justify-content-center">

                <h1>Пароль изменен!</h1>
                <div class="alert  alert-success  mt-3  mb-5">
                    <p>Ваш пароль был успешно изменен.</p>
                </div>
                <a href="{% url 'main' %}" class="text-decoration-none  text-center">На главную</a>

            </div>
        </div>
    </div>
</section>
{% endblock %}

authnapp/templates/authnapp/password_reset.html
{% extends "authnapp/base.html" %}

{% block title %}Сброс пароля{% endblock %}

{% block menu %}
    {% include 'authnapp/includes/inc_menu.html' %}
{% endblock menu %}

{% block content %}

<section class="password  mt-5">
    <div class="container  d-flex  justify-content-center">
        <div class="password__items">

            <h1 class="text-center  mb-5">Сброс пароля</h1>
            <div class="alert  alert-info  mb-5">Пожалуйста, введите Ваш Email</div>
            <form method="post">

                {% csrf_token %}
                {% for field in form %}
                    <div class="form-group">
                        {{ field.label }}
                        {{ field }}
                    </div>
                {% endfor %}

                <button type="submit" class="btn  btn-primary">Сброс</button>

            </form>

        </div>
    </div>
</section>
{% endblock %}

authnapp/templates/authnapp/password_reset_complete.html
{% extends "authnapp/base.html" %}

{% block title %}Reset your password{% endblock %}

{% block content %}
<section class="password  mt-5">
    <div class="container  d-flex  justify-content-center">
        <div class="password__items">

            <h1 class="mt-5 text-center">Пароль был сброшен!</h1>
 
        </div>
    </div>
</section>
    
{% endblock %}

authnapp/templates/authnapp/password_reset_confirm.html
{% extends "authnapp/base.html" %}

{% block title %}Reset your password{% endblock %}

{% block content %}
<section class="password  mt-5">
    <div class="container  d-flex  justify-content-center">
        <div class="password__items">

            <h1 class="mb-5">Введите новый пароль:</h1>
            <form enctype="multipart/form-data" method="post">
                {% csrf_token %}

                {% for field in form %}
                    <div class="form-group">
                        {{ field.label }}
                        {{ field }}
                    </div>

                    {% if field.errors %}
                        <div class="alert  alert-danger">
                            {{ field.errors }}
                        </div>
                    {% endif %}
                {% endfor %}

                <button type="submit" class="btn btn-success">Сбросить</button>
            </form>
            
        </div>
    </div>
</section>
{% endblock %}

authnapp/templates/authnapp/password_reset_done.html
{% extends "authnapp/base.html" %}

{% block title %}Reset your password{% endblock %}

{% block content %}
<section class="password  mt-5">
    <div class="container  d-flex  justify-content-center">
        <div class="password__items">

            <h1>Мы отправили вам E-mail</h1>
            <div class="alert  alert-info">Проверьте почтовый ящик, для получения подробных инструкций</div>

        </div>
    </div>
</section>
    
{% endblock %}

authnapp/templates/authnapp/password_reset_email.html
Someone asked for password reset for email {{ email }}. Follow thelink below:
{{ protocol }}://{{ domain }}{% url "auth:password_reset_confirm" uidb64=uid token=token %}
Your username, in case you've forgotten: {{ user.get_username }}

authnapp/templates/authnapp/register.html
{% extends 'authnapp/base.html' %}
{% load staticfiles %}

{% block menu %}
    {% include 'authnapp/includes/inc_menu.html' %}
{% endblock menu %}

{% block content %}

<div class="d-flex  justify-content-center  mt-5">
    <form class="form-horizontal  w-100  main-form" action="{% url 'auth:register' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ register_form.as_p }}
        <br>
        <input class="form-control" type="submit" value="зарегистрироваться">
    </form>
</div>

{% endblock %}

authnapp/templates/authnapp/verify.html
{% extends 'authnapp/base.html' %}
{% load staticfiles %}


{% block content %}
{% if user %}
<h3>Поздравляем!</h3>
<br>
<h4>Пользователь {{user.personal_account}} подтвержден.</h4>
{% else %}
<h3>Верификация не пройдена.</h3>
{% endif %}
<br>
<a href="{% url 'main' %}" class="btn  form-control" role="button"> на главную</a>

{% endblock %}